/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatMessages: typeof import('./src/components/ChatMessages.vue')['default']
    ChatPage: typeof import('./src/components/ChatPage.vue')['default']
    ConversationLiveChat: typeof import('./src/components/ConversationLiveChat.vue')['default']
    KnowledgeBase: typeof import('./src/components/KnowledgeBase.vue')['default']
    KnowledgeBaseDetails: typeof import('./src/components/KnowledgeBaseDetails.vue')['default']
    LiveChatHome: typeof import('./src/components/LiveChatHome.vue')['default']
    PoweredBy: typeof import('./src/components/PoweredBy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
